site_name: Papermege DMS
site_url: https://docs.papermerge.io
nav:
  - User Manual:
      - user/getting-started.md
      - user/general-concepts.md
      - user/user-interface.md
      - user/upload-documents.md
      - user/tags-and-folders.md
      - user/page-management.md
      - user/metadata.md
  - Setup:
    - setup/requirements.md
    - setup/downloading.md
    - setup/installation.md
    - setup/server_configuration.md
    - setup/backup.md
    - setup/upgrading.md
    - setup/docker.md
    - setup/settings.md
  - dev/index.md
  - settings.md
theme:
  name: material
  features:
  - search.suggest
  - search.highlight
#  - content.tabs.link
#  - navigation.indexes
  - content.tooltips
#  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite


