site_name: Papermege DMS
site_url: https://docs.papermerge.io
nav:
  - getting-started.md
  - User Manual:
      - user/general-concepts.md
      - user/user-interface.md
      - user/upload-documents.md
      - user/tags-and-folders.md
      - user/page-management.md
  - admin/index.md
  - dev/index.md
  - settings.md
theme: material
extra:
  version:
    provider: mike
