site_name: Papermerge 2.1
site_url: https://docs.papermerge.io
nav:
  - User Manual:
      - user/getting-started.md
      - user/user-interface.md
      - user/tags-and-folders.md
      - user/page-management.md
      - user/metadata.md
      - user/versions.md
      - user/automates.md
      - user/consumption.md
      - user/rest_api.md
      - user/ocr_languages.md
      - user/file_formats.md
      - user/document_pipelines.md
      - user/apps.md
      - user/glossary.md
  - Setup:
    - setup/overview.md
    - setup/requirements.md
    - setup/docker.md
    - setup/docker-compose.md
    - setup/backup.md
    - setup/upgrading.md
  - dev/index.md
  - settings.md
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - navigation.top
#  - content.tabs.link
#  - navigation.indexes
  - content.tooltips
#  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
repo_url: https://github.com/ciur/papermerge
extra:
  project: Papermerge  # custom variable for macros plugin
  version:
    provider: mike
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/ciur/papermerge
  - icon: fontawesome/solid/globe
    link: https://papermerge.com
extra_css:
  - css/custom.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
plugins:
  - macros

