site_name: Papermerge 3
site_url: https://docs.papermerge.io
nav:
  - Setup:
    - setup/overview.md
    - setup/requirements.md
    - setup/docker.md
    - setup/docker-compose.md
    - setup/ansible.md
    - setup/kubernetes.md
    - setup/authentification.md
    - setup/add-ocr-langs.md
  - User Manual:
    - user/getting-started.md
    - user/user-interface.md
    - user/upload-documents.md
    - user/tags.md
    - user/search.md
    - user/page-management.md
    - user/versions.md
    - user/merge-documents.md
    - user/ocr.md
    - user/file-formats.md
    - user/user-management.md
  - SSO:
    - sso/overview.md
    - OIDC:
      - sso/oidc/overview.md
      - sso/oidc/keycloak.md
      - sso/oidc/authentik.md
    - Remote User:
      - sso/remote-user/overview.md
      - sso/remote-user/authelia.md
  - Settings:
    - settings/overview.md
    - settings/auth.md
    - settings/main.md
    - settings/security.md
    - settings/ocr.md
    - settings/database.md
    - settings/redis.md
    - settings/search.md
  - "backup-restore.md"
  - REST API:
    - "rest-api/overview.md"
    - "rest-api/reference.md"
    - "rest-api/token.md"
  - Command Line Utilities:
    - cli/overview.md
    - cli/cli.md
  - Contributor Manual:
    - contributor/docker.md
  - "changelog.md"

theme:
  name: material
  custom_dir: overrides
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  logo: assets/logo.svg
  favicon: img/favicon.ico
  features:
  - search.suggest
  - search.highlight
  - navigation.top
#  - content.tabs.link
#  - navigation.indexes
  - content.tooltips
#  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - announce.dismiss
repo_url: https://github.com/ciur/papermerge
extra:
  project: Papermerge  # custom variable for macros plugin
  docker_image_version: 3.2  # latest docker image version e.g. 3.0, 3.0.1, 3.1.9, 3.0a1
  version:
    provider: mike
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/ciur/papermerge
  - icon: fontawesome/solid/globe
    link: https://papermerge.com
extra_css:
  - css/custom.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
plugins:
  - macros
  - search

