site_name: Papermerge DMS
site_url: https://docs.papermerge.io
nav:
  - User Manual:
      - user/getting-started.md
      - user/general-concepts.md
      - user/user-interface.md
      - user/upload-documents.md
      - user/tags-and-folders.md
      - user/page-management.md
      - user/metadata.md
  - Setup:
    - setup/requirements.md
    - setup/downloading.md
    - setup/installation.md
    - setup/server_configuration.md
    - setup/backup.md
    - setup/upgrading.md
    - setup/docker.md
    - setup/settings.md
  - dev/index.md
  - settings.md
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
#  - content.tabs.link
#  - navigation.indexes
  - content.tooltips
#  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
repo_url: https://github.com/ciur/papermerge
extra:
  version:
    provider: mike
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/ciur/papermerge
  - icon: fontawesome/solid/globe
    link: https://papermerge.com

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite


