[tool.poetry]
name = "documentation"
version = "1.4.13"
description = "Papermerge Documentation"
authors = ["Eugen Ciur <eugen@papermerge.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.10"
Sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"
sphinx-autobuild = "^2021.3.14"
sphinx-multiversion = "^0.2.4"
sphinxcontrib-httpdomain = "^1.8.0"

[tool.poetry.dev-dependencies]
taskipy = "^1.10.2"

[tool.taskipy.tasks]
autobuild = "sphinx-autobuild --port 9600 src/ _build/html/"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
