[tool.poetry]
name = "documentation"
version = "1.3.0"
description = "Papermerge Documentation"
authors = ["Eugen Ciur <eugen@papermerge.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.8"
Sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"
sphinx-autobuild = "^2021.3.14"
sphinx-multiversion = "^0.2.4"
sphinxcontrib-httpdomain = "^1.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
