name: Deploy 3.0 docs
on:
  push:
    branches:
      - "v3.0"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "v3.0"
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          pip3 install --upgrade setuptools
          pip3 install poetry
          poetry install --no-root
          poetry run mike deploy -p 3.0 latest --update-aliases
