name: Deploy Docs Version
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Docs Version
        options:
          - '2.0'
          - '2.1'
          - '3.0-dev'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install poetry
      - run: poetry install
      - name: Setup doc deploy
        run: |
          git fetch origin gh-pages --depth=1
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - run: poetry run mike deploy --push ${ inputs.version }
